export type Entry={word:string;meaning:string;zh:string;context:string;source:string};
export const articles=[
{category:'Environment',title:'The quiet value of a city tree',intro:'A little shade can change how a neighbourhood feels.',body:[
'On a hot afternoon, the difference between two neighbouring streets can be surprisingly large. One has a canopy of mature trees; the other has little shade. For someone walking to a bus stop, this difference is not merely aesthetic. It can determine whether the journey feels manageable.',
'Trees can mitigate heat by providing shade and releasing water through their leaves. Yet planting a tree is only the beginning. Young trees require consistent care, and their roots need enough space to grow. A planting target may sound impressive while concealing a more difficult question: how many trees will survive?',
'There is also a question of equity. If greener streets are concentrated in affluent neighbourhoods, residents elsewhere may receive fewer benefits. An effective plan would consider where shade is most needed, including routes to schools and public transport.',
'The lesson is that a visible action is not always the same as a lasting outcome. Counting newly planted trees is straightforward. Creating a resilient urban forest requires patience, maintenance and attention to the people who use the streets.'],words:[['canopy','The upper layer formed by the branches and leaves of trees.','樹冠'],['aesthetic','Connected with appearance or beauty.','美觀嘅；審美嘅'],['mitigate','To make something harmful less severe.','減輕；緩和'],['equity','Fairness that considers different needs and circumstances.','公平'],['affluent','Having a lot of money or resources.','富裕嘅'],['resilient','Able to cope with difficulties and recover.','有適應力嘅；有韌性嘅']]},
{category:'Technology',title:'When convenience asks for your attention',intro:'Why the easiest option is not always the one we intended.',body:[
'A notification promises something small: an update, a message or a recommendation. Opening it takes a second. Returning to the original task can take much longer. The cost of convenience is therefore not always obvious at the moment we accept it.',
'Digital services often anticipate what people might want next. This can reduce effort, but it can also blur the distinction between a deliberate choice and a habitual response. A person who opens an app for one purpose may leave having spent time on something entirely different.',
'The solution need not be to abandon technology. Removing unnecessary alerts introduces a little friction between an impulse and an action. That pause gives the user an opportunity to decide whether an interruption deserves attention.'],words:[['anticipate','To expect something and prepare for it.','預計；預先考慮'],['deliberate','Done intentionally, after considering a choice.','有意識嘅；經過考慮嘅'],['habitual','Done regularly, often without much thought.','習慣性嘅'],['friction','An obstacle or extra effort that slows an action.','阻力；額外步驟']]},
{category:'Business',title:'The repair shop around the corner',intro:'What changes when fixing something becomes easier?',body:[
'A broken appliance presents a familiar dilemma: repair it or buy another one. The decision depends on more than the price of a spare part. People also consider how long the repair will take and whether they can trust the result.',
'A nearby repair service can make an otherwise inconvenient choice feasible. Clear prices and reliable advice reduce uncertainty. However, repair businesses face constraints of their own, including access to parts and the time needed to diagnose an unfamiliar fault.',
'Encouraging repair therefore requires more than telling consumers to waste less. Products need to be designed with maintenance in mind. When repair is accessible and predictable, keeping an older item can become a practical choice rather than an exceptional effort.'],words:[['dilemma','A difficult choice between alternatives.','兩難局面'],['feasible','Possible and practical to do.','可行嘅'],['constraints','Limits that restrict what can be done.','限制'],['accessible','Easy to reach, obtain or use.','容易使用或取得嘅']]},
{category:'Culture',title:'A library with more than books',intro:'The everyday importance of a place open to everyone.',body:[
'A library may be one of the few indoor places where a person can stay without buying anything. Some visitors come for books, while others need a quiet desk or an internet connection. These purposes coexist within the same public space.',
'This variety can create tension. A lively group activity may disturb someone seeking silence. Rather than assuming that all visitors have identical needs, thoughtful design can allocate different areas to different activities.',
'The value of a library is therefore difficult to capture through borrowing figures alone. Its contribution also includes opportunities for people to participate in community life. Preserving that inclusive role requires listening to visitors who may use the building in very different ways.'],words:[['coexist','To exist together in the same place or time.','共存'],['allocate','To assign something for a particular purpose.','分配'],['inclusive','Welcoming people with different backgrounds and needs.','包容嘅']]},
{category:'Science',title:'What a single study can tell us',intro:'Reading research means looking beyond the headline.',body:[
'A headline may announce that one habit is linked to a better outcome. The finding could be useful, but a link is not automatically evidence that the habit caused the improvement. Other factors may influence both the behaviour and the result.',
'Researchers try to account for these factors, although no method removes every source of uncertainty. The composition of a sample also matters. A result observed in one group may not generalise to people living under different conditions.',
'This does not make research worthless. It means that conclusions should be proportionate to the evidence. Looking for consistent findings across several studies can provide a more nuanced understanding than treating a single result as a final answer.'],words:[['composition','The parts or people that make up something.','組成'],['generalise','To apply a finding beyond the group originally studied.','推廣至其他群體'],['proportionate','Appropriate in size or strength relative to something.','相稱嘅'],['nuanced','Recognising small but meaningful differences.','細緻嘅；考慮多方面嘅']]}
];
export function entryFor(index:number,word:string):Entry|undefined{const a=articles[index],v=a?.words.find(w=>w[0]===word.toLowerCase());if(!v)return;return {word:v[0],meaning:v[1],zh:v[2],context:a.body.flatMap(p=>p.match(/[^.!?]+[.!?]+/g)||[p]).find(s=>s.toLowerCase().includes(word.toLowerCase()))?.trim()||'',source:a.title};}
