'use client';
import {useState} from 'react';
import {ArrowLeft,Check,BookOpen,Volume2} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {type Entry} from './content';
import {Speaking} from './speaking';
import {type Lesson,newLesson,readLesson,correctSpelling,cloze,sentenceCheck} from '@/lib/practice';
export type Word=Entry&{id:string;due:number;stage:number;practice_json?:string;last_sentence?:string};
const titles=['Understand it','Spell it','Use the context','Say it aloud','Make it your own'];
export function Practice({word,onExit,onFinish}:{word:Word;onExit:()=>void;onFinish:()=>Promise<void>}){
 const [lesson,setLesson]=useState<Lesson>(()=>{const l=readLesson(word.practice_json);return l.completed?newLesson():l}),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[revealed,setRevealed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sentence,setSentence]=useState(()=>readLesson(word.practice_json).sentence),[compared,setCompared]=useState(false),[completed,setCompleted]=useState(false);
 const gap=cloze(word.context,word.word),hasGap=gap!==word.context;
 async function persist(next:Lesson,finish=false){setBusy(true);setError('');try{const r=await fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:word.id,lesson:next,finish})});const data:any=await r.json();if(!r.ok)throw new Error(data.error);setLesson(next);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function advance(patch:Partial<Lesson>={}){let step=lesson.step+1;if(step===2&&!hasGap)step=3;const next={...lesson,...patch,step};if(await persist(next)){setRevealed(false);setAnswer('');setFeedback('')}}
 async function check(){const ok=correctSpelling(answer,word.word);const key=lesson.step===1?'spelling':'gap';const next={...lesson,[key]:answer,help:lesson.help||!ok};if(await persist(next)){setFeedback(ok?'correct':'incorrect');setRevealed(true)}}
 async function finish(help:boolean){const next={...lesson,step:5,sentence,help:lesson.help||help,completed:true};if(await persist(next,true))setCompleted(true)}
 function listen(){if('speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word.word);u.lang='en-GB';u.rate=.8;window.speechSynthesis.speak(u)}else setError('Audio is unavailable in this browser.')}
 if(completed)return <div className="lesson-complete"><Check size={42}/><p className="eyebrow">WORD PRACTICE COMPLETE</p><h2>A word, made more familiar.</h2><h3>{word.word}</h3><p>{lesson.help?'This word will return in about 10 minutes.':'This word will return after a longer interval.'}</p><blockquote>{sentence}</blockquote><p className="lesson-note">Your sentence and lesson progress are saved in your notebook.{lesson.speaking==='skip'?' Speaking was skipped.':''}</p><button className="primary" onClick={async()=>{setBusy(true);try{await onFinish()}catch{setError('Saved, but the notebook could not refresh. Try again.')}finally{setBusy(false)}}} disabled={busy}>Back to practice</button>{error&&<p role="alert" className="error">{error}</p>}</div>;
 return <div className="lesson"><button className="back" disabled={busy} onClick={onExit}><ArrowLeft size={17}/>Pause lesson</button><div className="lesson-progress"><span>{titles[lesson.step]}</span><span>{lesson.step+1} / 5{!hasGap?' · context step skipped':''}</span></div><Progress value={lesson.step/5*100} aria-label="Lesson progress"/><div className="lesson-surface"><p className="eyebrow">{titles[lesson.step]}</p>{lesson.step===0&&<><h2>{word.word}</h2><p className="lesson-prompt">What does this word mean? Try explaining it in your own words.</p>{!revealed?<button className="primary" onClick={()=>setRevealed(true)}>Show explanation</button>:<><div className="explanation"><p>{word.meaning||'No meaning saved yet. You can add one in your notebook.'}</p>{word.zh&&<p className="chinese">{word.zh}</p>}{word.context&&<blockquote>{word.context}</blockquote>}</div><div className="lesson-actions"><button className="secondary" disabled={busy} onClick={()=>advance({help:true})}>I’m learning this</button><button className="primary" disabled={busy} onClick={()=>advance()}>I remembered</button></div></>}</>}
{(lesson.step===1||lesson.step===2)&&<><h2>{lesson.step===1?'Which word is it?':'Complete the sentence.'}</h2>{lesson.step===1?<><p className="lesson-prompt">{word.meaning||'Listen, then type the word you saved.'}</p>{word.zh&&<p className="chinese">{word.zh}</p>}<button className="back audio-hint" onClick={listen}><Volume2 size={18}/>Listen to the word</button></>:<blockquote>{gap}</blockquote>}<form onSubmit={e=>{e.preventDefault();check()}}><label className="lesson-label" htmlFor="spelling">{lesson.step===1?'Type the word':'Fill in the gap'}</label><input id="spelling" className="lesson-input" value={answer} maxLength={100} onChange={e=>{setAnswer(e.target.value);setFeedback('');setRevealed(false)}} autoComplete="off" autoCorrect="off" autoCapitalize="none" spellCheck={false} disabled={busy} required/>{!revealed&&<button className="primary" type="submit" disabled={busy||!answer.trim()}>Check answer</button>}</form>{revealed&&<div className={'lesson-feedback '+(feedback==='correct'?'right':'retry')} role="status"><b>{feedback==='correct'?'That’s right.':'Not quite—look closely at the spelling.'}</b><p>The word is <strong>{word.word}</strong>.</p><p>{word.meaning}</p><button className="primary" disabled={busy} onClick={()=>feedback==='correct'?advance():(setAnswer(''),setFeedback(''),setRevealed(false))}>{feedback==='correct'?'Continue':'Try spelling it again'}</button></div>}</>}
{lesson.step===3&&<><h2>{word.word}</h2><p className="lesson-prompt">Listen to the word, then say it yourself.</p><fieldset disabled={busy}><Speaking word={word.word} onDone={skipped=>advance({speaking:skipped?'skip':'done'})}/></fieldset></>}
{lesson.step===4&&<><h2>Write your own sentence.</h2><p className="lesson-prompt">Use <strong>{word.word}</strong> in a sentence about something familiar to you.</p><p className="definition-reminder">{word.meaning}</p><label className="lesson-label" htmlFor="sentence">Your sentence</label><textarea id="sentence" className="lesson-input" value={sentence} maxLength={1500} onChange={e=>{setSentence(e.target.value);setCompared(false);setFeedback('')}} placeholder={'Try using “'+word.word+'”…'}/>{!compared?<button className="primary" disabled={busy||!sentence.trim()} onClick={async()=>{const problem=sentenceCheck(sentence,word.word);if(problem){setFeedback(problem);return}if(await persist({...lesson,sentence})){setCompared(true);setFeedback('')}}}>Compare with the meaning</button>:<div className="sentence-comparison"><p><Check size={16}/> You included the word in a sentence.</p><p className="lesson-note">This checks the target word and length only. Compare your meaning and grammar yourself.</p>{word.context?<blockquote>{word.context}</blockquote>:<p>{word.meaning}</p>}<p>Does your sentence use the word with this meaning?</p><div className="lesson-actions"><button className="secondary" disabled={busy} onClick={()=>finish(true)}>I need more practice</button><button className="primary" disabled={busy} onClick={()=>finish(false)}>Yes, finish lesson</button></div></div>}{feedback&&<p className="error" role="status">{feedback}</p>}</>}{error&&<p className="error" role="alert">{error}</p>}</div><p className="lesson-note progress-note"><BookOpen size={15}/> Completed steps save automatically. Unsubmitted text stays here until you leave.</p></div>
}
