'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Volume2} from 'lucide-react';
export function Speaking({word,onDone}:{word:string;onDone:(skipped:boolean)=>void}){
 const [recording,setRecording]=useState(false),[pending,setPending]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),audioUrl=useRef(''),alive=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function stop(){if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);setRecording(false)}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);window.speechSynthesis?.cancel()}},[]);
 function listen(){setError('');if(!('speechSynthesis'in window)){setError('Spoken audio is unavailable in this browser. You can practise aloud and continue.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-GB';u.rate=.8;u.onerror=()=>{if(alive.current)setError('Audio could not play. Please try again.')};window.speechSynthesis.speak(u)}
 async function record(){setError('');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('Recording is unavailable here. Open in Safari, or practise aloud without recording.');return}setPending(true);try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;window.speechSynthesis?.cancel();const r=new MediaRecorder(s);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{s.getTracks().forEach(t=>t.stop());if(!alive.current)return;if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current=URL.createObjectURL(new Blob(chunks,{type:r.mimeType}));setUrl(audioUrl.current);setRecording(false)};r.onerror=()=>{stop();setError('Recording stopped unexpectedly. Try again or practise aloud.')};r.start();setRecording(true);timer.current=setTimeout(stop,20000)}catch{stream.current?.getTracks().forEach(t=>t.stop());if(alive.current)setError('Microphone access was not available. You can allow it in Safari or practise aloud.')}finally{if(alive.current)setPending(false)}}
 return <div className="speaking"><div className="lesson-actions"><button className="secondary" disabled={recording} onClick={listen}><Volume2 size={18}/>Listen</button><button className="secondary" disabled={pending} onClick={recording?stop:record}>{recording?<Square size={18}/>:<Mic size={18}/>} {pending?'Opening microphone…':recording?'Stop recording':url?'Record again':'Record yourself'}</button></div>{recording&&<p role="status">Recording… stops after 20 seconds.</p>}{url&&<div className="recording-playback"><label>Your recording</label><audio controls src={url}/></div>}{error&&<p role="status" className="error">{error}</p>}<p className="lesson-note">Listen, say the word, and compare the sounds. This is self-assessed; there is no automatic pronunciation score. Your recording stays in this tab and is discarded when you leave.</p><div className="lesson-actions"><button className="primary" disabled={recording||pending} onClick={()=>onDone(false)}>I practised aloud</button><button className="back" disabled={recording||pending} onClick={()=>onDone(true)}>Skip speaking</button></div></div>
}
